add `directoryd` and `directory-cli` binary apps
citadel-tech/coinswap pull request #187
Opened 2024-06-24 15:45 UTC by keraliss

This PR aims to add `directoryd` and `directory-cli` binary apps, and resolve the help text bug that was occurring on running directory server app

2024-07-20 12:23 UTC, mojoX911 requested changes
Ack. Few nits.

2024-07-20 12:23 UTC, mojoX911 commented on src/market/rpc/server.rs
> +    // read this
remove this comment. Or change it to something relevant like "start the server loop".

2024-07-20 12:23 UTC, mojoX911 commented on src/market/directory.rs
> +    // start directory rpc server here
Remove comment.

2024-07-22 03:02 UTC, keraliss commented on src/market/directory.rs
> +    // start directory rpc server here
yeah sorry, completely missed these!

2024-07-22 05:17 UTC, mojoX911 approved these changes
ACK

2024-07-22 05:17 UTC, merged