macos aarch64 build issue
citadel-tech/coinswap pull request #188
Opened 2024-06-25 05:15 UTC by 007harshmahajan

RESOLVE #127

2024-06-25 05:17 UTC, 007harshmahajan commented
and run following command for build
`cargo build --target=aarch64-apple-darwin  --features=vendored-openssl`

2024-06-25 18:25 UTC, Shourya742 commented
This solution works, but if possible, could we have a Dockerfile that supports cross-compilation? This would allow it to function not only on M1 chip Macs but also on Windows. Otherwise, we will need to continuously add libraries to mitigate build issues. 

@mojoX911, let me know your thoughts on this.

2024-06-26 12:12 UTC, mojoX911 commented
> This solution works, but if possible, could we have a Dockerfile that supports cross-compilation? This would allow it to function not only on M1 chip Macs but also on Windows. Otherwise, we will need to continuously add libraries to mitigate build issues.

Yes we should. Can you turn this into an Issue so we can track for later? 

Is this PR good to go?

2024-06-26 12:34 UTC, 007harshmahajan commented
docker works, nice compatiblity ahead, we can close PR but ig let issue be open as working with `rust-analyser` makes local compilation, im not sure can we use it with docker instance, @Shourya742 help us on it

2024-06-30 07:31 UTC, mojoX911 requested changes

2024-06-30 07:31 UTC, mojoX911 commented on Cargo.toml
> +vendored-openssl = ["openssl-sys/vendored"]
As discussed in the dev call, let's change this to `build-mac-os`, that's a more clear name. 

Add a comment above as a todo for adding more platform-specific build support.

We can create two different follow-up issues on of this.

- Short term: Add more platform specific fix so more devs can run it wherever they need to.
- Long term: Create a docker based solution that can run on any platform.
- Even Longer term: Ensure **Reproducible Builds** for all the apps and deamons.

For now, I am inclined to merge this as a short-term fix for #127 .

2024-06-30 08:07 UTC, 007harshmahajan commented
UPDATE : feature tag for macos compilation 
compile with 
`cargo build --target=aarch64-apple-darwin  --features=build-macos-aarch`

2024-06-30 08:13 UTC, mojoX911 commented
> compile with
cargo build --target=aarch64-apple-darwin  --features=build-macos-aarch

We need to add this in readme too. Do they need --target if they are already compiling on native platform?

2024-06-30 08:17 UTC, 007harshmahajan commented
will add that to readme 
no need `target` for existing compilation as rust takes this info from system calls, just need that for macos (M series)

2024-06-30 16:44 UTC, Shourya742 requested changes
It works fine on all macOS chipsets. Just squash the commits into a single commit.

2024-07-01 03:08 UTC, Shourya742 reviewed
@007harshmahajan Can you sign your commits?

2024-07-01 11:20 UTC, Shourya742 requested changes
One last nit

2024-07-01 11:20 UTC, Shourya742 commented on Cargo.toml
> +
```suggestion

```

2024-07-01 11:36 UTC, 007harshmahajan commented on Cargo.toml
> +
done

2024-07-01 12:07 UTC, Shourya742 approved these changes
ACK 70bfccf2400ce6316df5ec79c4c8218a84d1a1ce

2024-07-01 12:28 UTC, mojoX911 approved these changes
ACK

2024-07-01 12:29 UTC, merged