set `Current height` as locktime for `Contract` & `Funding` tx.
citadel-tech/coinswap pull request #230
Opened 2024-08-10 05:08 UTC by KnowWhoami

Fix #229

2024-08-14 05:43 UTC, mojoX911 reviewed
Approach Ack. Something broke in the tx construction which is failing the test.

2024-09-03 07:14 UTC, Shourya742 requested changes
Concept ACK. I will through review this soon. Need to get around the idea of snipping. Till then just remove the unwraps and propagate them.

2024-09-03 07:14 UTC, Shourya742 commented on src/wallet/direct_send.rs
> +        let lock_time = LockTime::from_height(current_height as u32).unwrap();
Remove these unwraps..

2024-09-03 07:14 UTC, Shourya742 commented on src/wallet/funding.rs
> +            let lock_time = LockTime::from_height(current_height as u32).unwrap();
Same for this

2024-09-03 08:05 UTC, mojoX911 reviewed
ACK.. Looking good. minor nits as mentioned by @Shourya742

2024-09-03 08:05 UTC, mojoX911 commented on src/wallet/swapcoin.rs
> +            // TODO: left to check.
This TODO still applies?

2024-09-04 09:08 UTC, mojoX911 commented on src/protocol/contract.rs
> +    const TEST_CURRENT_HEIGHT: u32 = 100;
It doesn't matter. Yes generally const are architectural components. In tests you can just hard code the value. Nothing is affected in runtime either way.

2024-09-04 09:10 UTC, mojoX911 approved these changes
ACK 02333ec946d3ff0b153937d5e7e90f13f144ad35

2024-09-04 09:10 UTC, mojoX911 commented on src/wallet/swapcoin.rs
> +    const TEST_CURRENT_HEIGHT: u32 = 100;
For the sake of consistency, it makes sense. Doesn't impact anything serious if we don't.

2024-09-04 09:11 UTC, mojoX911 commented
@KnowWhoami Green from me to merge. 

If you have more improve ideas can be done in a follow-up PR. 

@Shourya742 if it looks good to you we can merge.

2024-09-05 11:10 UTC, Shourya742 approved these changes
ACK

2024-09-05 11:10 UTC, merged