replace `config_path` by `data_dir` in directory initialization
citadel-tech/coinswap pull request #277
Opened 2024-10-11 04:26 UTC by claddyy

Currently we give config_path as parameter to the directory server initialization. But we want to provide it directory, and then it should derive the config_path in using directory, not the other way around.
https://github.com/citadel-tech/coinswap/blob/291187157da01e7b33f10f706e428701de7d88b2/src/market/directory.rs#L66-L70

2024-10-12 14:44 UTC, mojoX911 requested changes
Ack.

few more touches and its good to go.

2024-10-12 14:44 UTC, mojoX911 commented on src/market/directory.rs
> +        directory: Option<PathBuf>,
For sake of consistency with Maker and Taker, lets call it `data_dir`.

2024-10-12 14:44 UTC, mojoX911 commented on src/market/directory.rs
> +
remove extra new lines.

2024-10-12 14:44 UTC, mojoX911 commented on src/market/directory.rs
> +        // let data_dir = config_path.parent().unwrap().to_path_buf();
both lines can be removed.

2024-10-12 17:30 UTC, claddyy commented
> Ack.
> 
> few more touches and its good to go.

Addressed the comments 726bd95775599ddc0cd60ae28952e96f97f7c88e

2024-10-13 07:34 UTC, mojoX911 approved these changes
ACK 726bd95775599ddc0cd60ae28952e96f97f7c88e

2024-10-13 08:35 UTC, Shourya742 approved these changes
ACK

2024-10-13 08:44 UTC, merged