Add loop in bufreader in rpc server
citadel-tech/coinswap pull request #286
Opened 2024-10-25 13:51 UTC by claddyy

Adding a loop at the point where we're reading the buffer while making rpc requests.

Issue: Getting `failed to fill whole buffer` while making a POST request.
For linux we won't face this, but for mac, we do, as the file descriptors don't get immediately filled and usually, a time lag is observed for macos.

2024-10-25 16:21 UTC, Shourya742 commented on src/market/rpc/server.rs
> +            }
Can you make this change to read_message?

2024-10-27 07:10 UTC, mojoX911 approved these changes
Ack

2024-10-27 09:04 UTC, Shourya742 requested changes
Minor nit, and we are good to go..

2024-10-27 09:04 UTC, Shourya742 commented on src/utill.rs
> +            Err(e) if e.kind() == ErrorKind::Interrupted => continue,
Can be clubbed.
```suggestion
            Err(e) if matches!(e.kind(), ErrorKind::WouldBlock | ErrorKind::Interrupted) => continue,
```

2024-10-27 13:22 UTC, Shourya742 approved these changes
ACK

2024-10-27 13:22 UTC, merged