use `AtomicBool` instead of `RwLock`
citadel-tech/coinswap pull request #289
Opened 2024-11-01 06:23 UTC by KnowWhoami

This pr is a continuation of #274 which aims to use `AtomicBool` instead of `Rwlock`.

2024-11-02 07:01 UTC, mojoX911 approved these changes
Ack

2024-11-05 05:12 UTC, Shourya742 requested changes
Can you test if there is any performance improvement or not?

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort1.rs
> +use std::sync::atomic::Ordering::Relaxed;
Add this to std below

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort1.rs
> +    //     .for_each(|maker| maker.shutdown.store(true, Relaxed));
why do we have these comments,?

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort2_case1.rs
> +use std::sync::atomic::Ordering::Relaxed;
move this

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort3_case1.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort3_case2.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort3_case3.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/fidelity.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/malice1.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/malice2.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/standard_swap.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-05 05:12 UTC, Shourya742 commented on tests/abort2_case2.rs
> +use std::sync::atomic::Ordering::Relaxed;
move

2024-11-08 06:20 UTC, Shourya742 requested changes
I see you’ve marked all requested changes as resolved, but I don’t see any of them implemented. Could you add the changes and rebase? It looks like this PR has some conflicts, so please resolve those as well. It looks good to go once these changes are in place.

2024-11-17 17:19 UTC, mojoX911 approved these changes
reAck

2024-11-18 03:41 UTC, Shourya742 commented
> > Can you test if there is any performance improvement or not?
> 
> As we are handling small bunch of threads which are accessing these variables values at a fixed time interval so it has less probability of having collisions and since those mutex locks are hold and released in negligible time so I don't think so there will be much significant performance improvement.
> 
> Though this helps to simply our code structures by removing unnecessary complexity and api's.

Based on your this assertion, I would nack this PR.

2024-11-18 03:45 UTC, Shourya742 approved these changes

2024-11-18 03:45 UTC, merged