use `feerate` instead of `fee` while sending a transaction
citadel-tech/coinswap pull request #343
Opened 2024-12-24 13:18 UTC by claddyy

closes #309
The code doesn't compile and needs more work. 
I'm drafting this PR to get a `ConceptACK`.

2025-01-15 13:55 UTC, mojoX911 commented
@claddyy this is medium priority, and we wanna get this in 1.1 release. So if you can resume work on this we can conclude it as soon as possible.

2025-01-18 00:13 UTC, claddyy commented on src/wallet/direct_send.rs
> +const P2WSH_MULTISIG_2OF2_WITNESS_SIZE: usize = 222;
Since we are skipping the contract Tx, I've not hardcoded values for witness size for other cases. 

The witness size already contains the signature size as well as pub keys.

2025-01-18 08:01 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +const P2WSH_MULTISIG_2OF2_WITNESS_SIZE: usize = 222;
We are skipping them in this API, as we can't "direct send"  them. But they are being spent in recovery process and there are apis to create a hashlock or timelock spend which will need this size calculation.

2025-01-18 08:25 UTC, mojoX911 requested changes
Initial concept ack. Needs some more polishes.

2025-01-18 08:25 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
This doesn't have to be 0. You can set it to the actual value needed here only.

2025-01-18 08:25 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +        }
why do the same thing twice?

2025-01-18 08:25 UTC, mojoX911 commented on src/wallet/direct_send.rs
>          if let SendAmount::Amount(amount) = send_amount {
This is going to change the tx size again. so the fee needs to be recalculated if we add change out put. It needs to be a 2 steps process.

- First create the tx without change, find size, find total fees, check if change is needed.
- If change is needed, add change output with 0 fees, recalculate size, recalculate fees and find the exact change amount.

2025-01-18 08:25 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +        let vsize = (base_size * 4 + total_witness_size) / 4;
we need to assert that this calculation is right. Easy way is, after the tx is signed, find the total vsize again, and match with this calculated number. put that as an `assert!` in the code.

2025-01-19 10:22 UTC, claddyy commented on src/wallet/direct_send.rs
> +        }
Happened by mistake.

2025-01-19 10:25 UTC, claddyy commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
I'm validating `send_amount` against fee parameters later, that's why I kept it 0, and the value is added later. Does keeping it this way makes more sense, or shall I change it?

2025-01-19 10:26 UTC, claddyy commented on src/wallet/direct_send.rs
>          if let SendAmount::Amount(amount) = send_amount {
Addressed 1d94e2c7eb817b2f5c05930039f2e0e860f85544

2025-01-19 10:26 UTC, claddyy commented on src/wallet/direct_send.rs
> +        let vsize = (base_size * 4 + total_witness_size) / 4;
Addressed 0b1819d491ec45eb3fcbdf7438f3fa38aa54fc7b

2025-01-21 07:00 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
Change it, please. There is no ambiguity about the send amount. Just set the value here. 

This approach makes sense for change amount where you don't know the value before hand.

2025-01-21 07:20 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +                );
There is one edge case to consider here. because `feewchange` will be higher than the previous calculated fee, if the `remaining` is close to dust limit, this updated `remaining` value may be below dust after recalculation. Which will make the added change below dust limit.

This can be handled by creating an hypothetical `remianing_with_change` value first, and then check if that is less than dust. Only add change out if true, else carry on with the non-change calculation.

2025-01-21 07:28 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
Ah I see, you need this to handle the max spend case. Cool then it can stay.

2025-01-21 07:43 UTC, mojoX911 requested changes

2025-01-21 07:43 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +                }
I think this logic can be moved to the call sites, or better, create wrapper APIs on top of a common send API. Weather a utxo is valid for spend should be determined at the call site. 

For ex: if you wanna spend only fidelity bonds in API like `spend_fildiety()` you filter out the fidelity utxo, and then feed to the common `spend_coins()` API.

This will also allow us to use a common logic for all kind of spendings and use that everywhere, instead of current individual design of each spend functions. This refactor is much needed.

2025-01-21 07:57 UTC, mojoX911 commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
One good way of doing it would be to have a `SpendType` enum.

````
pun enum SpendType {
    Amount(u64),
    NoChange
```

When `NoChange` is given, it will create a change less tx, sending the whole `total_input - fee` to the `dest_addr`. This will be useful for fidelity, and contract spendings.

2025-01-27 04:32 UTC, claddyy commented on src/wallet/direct_send.rs
> +                );
Nice catch! Addressed d0e8a5b165d26a0e8a4c34a5b126f20814e51044

2025-01-27 04:35 UTC, claddyy commented on src/wallet/direct_send.rs
> +                }
Makes sense. Partially addressed via aec4eec7485d3d8fe387df1c51299051d7d229b4.
I'll try once to get the `size` of tx using the descriptor instead of current workaround(hardcoding witness sizes). Once that's done, the API would be lot cleaner.

2025-01-27 04:41 UTC, claddyy commented on src/wallet/direct_send.rs
> +            value: Amount::ZERO, //Temporary value
> One good way of doing it would be to have a `SpendType` enum.
> 
> ```rust
> pun enum SpendType {
>     Amount(u64),
>     NoChange
> }
> ```
> 
> When `NoChange` is given, it will create a change less tx, sending the whole `total_input - fee` to the `dest_addr`. This will be useful for fidelity, and contract spendings.

https://github.com/claddyy/coinswap/blob/d0e8a5b165d26a0e8a4c34a5b126f20814e51044/src/wallet/direct_send.rs#L201-L204

SpendType seems to be just same as the SendAmount enum. Currently when `Max` is given, the change less tx is created.

2025-02-03 13:56 UTC, mojoX911 requested changes
looking good so far. few more tasks before completion.

- Simplify the `spen_coins` function and use it for all types of spend cases. This will reduce code and make it consistent everywhere.

- Make the tests and asserts pass.

2025-02-12 00:11 UTC, VanshulB commented on src/wallet/fidelity.rs
> +        let mut fee = Amount::from_sat((fee_rate * (vsize as f64)).ceil() as u64);
If we were to create a `spend_coins` API for handling all transaction creation, how would we manage Timelocks and Hashlocks? Currently, the implementation requires the contract transaction and the timelock value when creating `TxIn` in the case of Timelock and Hashlock.
It seems like `spend_coins` would be well-suited for direct spending and fidelity transactions, while a separate API might be better for handling Hashlocks and Timelocks since they require contract transactions while creating `TxIn`. Would it make sense to have a dedicated API for contract transactions instead? Let me know how you think we should proceed!

2025-02-27 08:25 UTC, mojoX911 commented
superseded by #418

2025-02-27 08:25 UTC, closed without merging