Fix stuffs
citadel-tech/coinswap pull request #351
Opened 2024-12-28 14:12 UTC by mojoX911

2025-01-02 16:09 UTC, KnowWhoami commented on src/bin/maker-cli.rs
> +    ListUtxoSwap,
nit: 
``` suggestion
    ListSwapUtxo,
```    
similarly for others too.

2025-01-02 16:10 UTC, KnowWhoami commented on src/bin/maker-cli.rs
> +    GetBalanceSwap,
nit: 
``` suggestion
    GetSwapBalance
```

similarly for others too.

2025-01-02 16:13 UTC, KnowWhoami commented on src/bin/makerd.rs
> +/// The server requires a Bitcoin Core RPC connection running in Signet. It requires some starting balance (0.05 BTC Fidelity + Swap Liquidity).
It requires some more amount for creating normal txes too.

2025-01-02 16:15 UTC, KnowWhoami commented on src/bin/makerd.rs
> +/// The server requires a Bitcoin Core RPC connection running in Signet. It requires some starting balance (0.05 BTC Fidelity + Swap Liquidity).
Why we require Bitcoin-core rpc on `signet`?
It can run on any networks.
In demo-doc -> we just need to show the working in signet.

2025-01-02 16:34 UTC, KnowWhoami commented on src/bin/maker-cli.rs
> +    GetBalance,
nit: 
```suggestion
    GetSpendableBalance,
```

2025-01-02 16:35 UTC, KnowWhoami commented on src/bin/taker.rs
> -    SeedUtxo,
same here.

2025-01-03 13:23 UTC, mojoX911 commented on src/wallet/api.rs
>      pub fn balance(&self) -> Result<Amount, WalletError> {
taken

2025-01-03 13:26 UTC, mojoX911 commented on src/bin/taker.rs
> +    FetchOffers,
The only other time the user can fetch offers is at coinswap. If they haven't swaped for a long time, the offerbook will be outdated. 

The trade-off here is to give users an option to update the book without initiating a swap. We should also have a `list-offers` command, that just lists the current book. but we can do it later. needs a bit more careful thinking all around offerbook stuffs.

2025-01-03 13:27 UTC, mojoX911 commented on src/bin/taker.rs
> +    FetchOffers,
marked a TODO.

2025-01-03 13:34 UTC, mojoX911 commented on src/bin/taker.rs
> +    ListUtxo,
IMO live contracts are also spendable. They don't occur often, but when they do they should be spendable.

For now this is fine. We need to find more clearer ways to describe these to the users. There are different kinds of utxos floating around, and they need to be explained properly.

marking TODO.

2025-01-03 13:34 UTC, mojoX911 commented on src/bin/taker.rs
> +                bitcoin::consensus::encode::serialize_hex(&tx.compute_txid())
covered.

2025-01-03 13:37 UTC, mojoX911 commented on src/bin/taker.rs
> +        #[clap(name = "send_amount", default_value = "500000")]
No hard opinions. It could be useful. was helpful in my testing at least. just the `coinswap` command then works deterministically. doesn't hurt keeping either. if feels redundant will remove later.

2025-01-03 13:41 UTC, mojoX911 commented on src/bin/maker-cli.rs
problem here is, we need to explain whats a "seed" utxo, which clearly is a very bad word to use for this context. Instead we should name all of them more clearly later.

Currently changed the `list-utxo/get-balance` to reflect the total `spendable balance : seed + swap + contract`.

So this instead gives the whole utxo list to users, instead of a ctaegory misnomer category "seed".. And yes they need to find utxos manually for now. That also needs to be improved later.

2025-01-03 13:42 UTC, mojoX911 commented on src/bin/makerd.rs
> +    let conn_type = ConnectionType::TOR;
covered. tests runs in clearnet only.

2025-01-03 13:43 UTC, mojoX911 commented on src/bin/directoryd.rs
> +    let conn_type = ConnectionType::TOR; // Remove the hardcode when we multi-network feature open.
overridden.

2025-01-03 13:43 UTC, mojoX911 commented on src/maker/api.rs
> +            config.network_port = port;
taken.

2025-01-03 13:44 UTC, mojoX911 commented on src/bin/tor.rs
> +}
bootstrapping log added.

2025-01-03 13:46 UTC, mojoX911 commented on src/tor.rs
> +        }
Ack. will be much cleaner. but not doing in this push. marked a todo.

2025-01-03 13:47 UTC, mojoX911 commented on src/maker/rpc/server.rs
> +                    continue;
removed.

2025-01-03 13:48 UTC, mojoX911 commented on src/utill.rs
> +                        return Err(io::Error::new(io::ErrorKind::Other, "Error reading line"));
marked as todo, has to be done later.

2025-01-03 13:48 UTC, mojoX911 commented on src/maker/server.rs
> +            if rpc_ping_success == false {
was a clippy issue, covered.

2025-01-03 13:50 UTC, mojoX911 commented on src/maker/server.rs
> +            // Hard error here, because monitor_log_for_completion doesn't work with existing file.
didn't get it. if it exists seems like it will always find the "100%" tag and will not wait. Will look into this deeper later. marked as todo.

2025-01-03 13:53 UTC, mojoX911 commented on src/market/directory.rs
> +                log::info!("tor is ready!!");
changed to `tor is ready!` everywhere.

2025-01-03 13:57 UTC, mojoX911 commented on src/taker/api.rs
> +        };
no `write_to_disk` errors if path doesn't exist.

2025-01-03 13:58 UTC, mojoX911 commented on src/taker/offers.rs
> +    pub fn all_good_makers(&self) -> Vec<&OfferAndAddress> {
Offerbook has to be re though later. Marked as todo.

2025-01-03 14:02 UTC, mojoX911 commented on src/taker/api.rs
>              }
theres a dedicated tor module. all tor codes can be moved there.

2025-01-03 14:03 UTC, mojoX911 commented on src/bin/maker-cli.rs
> +    GetBalanceSwap,
no. this jumbles the help command. help commands are sorted alphabetically.. keeping the category as the second word makes all commands of same category to list together.

2025-01-03 14:07 UTC, mojoX911 commented on src/bin/makerd.rs
> +/// The server requires a Bitcoin Core RPC connection running in Signet. It requires some starting balance (0.05 BTC Fidelity + Swap Liquidity).
the liuve network will be running on signet. the default network at release has to be signet. regtest only works for devs who has all the systems locally. Users can't try swap without signet.

Specific mention here, because its important for people to be in the same network to swap. technically it can work on testnet too. but if different people are on different network it wont work.. 

everybody has to be in the same network as our first DNS. Which will be in signet. thus its as good as effectively hardcoding in everybody to Signet. people can try other networks but there no DNS, so nothing will happen.

2025-01-03 14:21 UTC, KnowWhoami commented on src/bin/maker-cli.rs
yeah, makes sense then.
mark  it as  TODO  to keep track of it.

2025-01-03 14:21 UTC, KnowWhoami commented on src/maker/rpc/messages.rs
> +    ServerError(String),
I think, we should also add this error variant to DNS rpc messages too.

2025-01-03 14:21 UTC, KnowWhoami commented on src/taker/api.rs
>              }
raised an issue for that. #363

2025-01-03 14:21 UTC, KnowWhoami commented on src/bin/makerd.rs
> +/// The server requires a Bitcoin Core RPC connection running in Signet. It requires some starting balance (0.05 BTC Fidelity + Swap Liquidity).
yeah,makes sense.

2025-01-03 14:27 UTC, mojoX911 commented on src/maker/rpc/messages.rs
> +    ServerError(String),
Later.

2025-01-03 14:28 UTC, mojoX911 commented on src/bin/makerd.rs
> +/// The server requires a Bitcoin Core RPC connection running in Signet. It requires some starting balance (0.05 BTC Fidelity + Swap Liquidity).
Total minimum coing out to be 0.1. Which could be too much. Discussion in discord.

2025-01-03 14:28 UTC, mojoX911 commented on src/bin/maker-cli.rs
> +    GetBalance,
Spendable is implied.

2025-01-03 14:28 UTC, mojoX911 commented on src/bin/taker.rs
> -    SeedUtxo,
now returning all utxos.

2025-01-03 14:36 UTC, KnowWhoami commented on src/bin/makerd.rs
>          default_value = "127.0.0.1:18443"
If we are moving to signet then let's just change the port to `38332` (signet default port)

2025-01-03 15:26 UTC, mojoX911 commented on src/bin/makerd.rs
>          default_value = "127.0.0.1:18443"
will be changed after deployment.

2025-01-07 09:23 UTC, KnowWhoami commented on src/maker/server.rs
> +                    let port = port.clone(); // If needed
What's the need of cloning port?

2025-01-07 15:01 UTC, mojoX911 commented on src/wallet/fidelity.rs
> +                                "Use `maker-cli redeem-fildeity <index>` to redeem the bond"
>  should we make index as postional agrument having default value as 0?

We should present these bonds better. For now its the shortest solution to work with, so going with it.

> Instead, only log this message when the error is of FidelityError::BondLocktimeExpired type.

Taken.

2025-01-07 15:05 UTC, mojoX911 commented on src/wallet/fidelity.rs
> +        // No need to wait for confirmation as that will delay the rpc call. Just send back the txid.
In other words, it can never happen. There are some nice patterns of hashmap to get that behavior without unwraps.  For now I will keep it as it is.

2025-01-07 15:07 UTC, mojoX911 commented on src/market/rpc/server.rs
> +            send_message(socket, &resp)?;
It was a redundant log, the same log is added in `start_rpc_server`.

2025-01-07 15:09 UTC, mojoX911 commented on src/maker/server.rs
> +        log::info!("No active Fidelity Bonds found. Creating one.");
changed it to wallet balance. lets throw away the term seed balance forever. At user level, one only cares about spendable and unspendable balance. We will improve that later.

2025-01-07 15:16 UTC, mojoX911 commented on src/maker/api.rs
> +
Nice point. Adding the refresh into every wallet sync. That should keep it updated all the time.

2025-01-07 15:27 UTC, mojoX911 commented on src/bin/makerd.rs
> +/// So topup with at least 0.001 BTC to start all the node processses. Suggested faucet: https://signetfaucet.com/
updated.

2025-01-08 13:26 UTC, KnowWhoami commented on src/bin/maker-cli.rs
> +/// For more detailed usage information, please refer: https://github.com/citadel-tech/coinswap/blob/master/docs/app%20demos/maker-cli.md
![image](https://github.com/user-attachments/assets/dc59c4b5-59ea-462a-b2d4-4ac4e48899a9)

This fidelity  bond data in `maker-cli` is displayed in wierd way on github -> it's because we are using `json` instead of `bash` here: 
https://github.com/citadel-tech/coinswap/blob/dd0243d0e5f8fb52a67c7cb7a2efeb35a81c12b0/docs/app%20demos/maker-cli.md?plain=1#L164

2025-01-08 13:26 UTC, KnowWhoami commented on README.md
>  Additionally, note that this code is currently designed to run exclusively on Linux systems.
would be better to mention that Currently coinswap is active only on `tor` currently.
Multi-network feature would come in future releases.

2025-01-08 13:26 UTC, KnowWhoami commented on README.md
> +  `taker`: The swap client app. This acts as a regular bitcoin wallet with swap capability. App dmeo [here](https://github.com/citadel-tech/coinswap/blob/master/docs/app%20demos/taker-tutorial.md)
```suggestion
  `taker`: The swap client app. This acts as a regular bitcoin wallet with swap capability. App demo [here](https://github.com/citadel-tech/coinswap/blob/master/docs/app%20demos/taker-tutorial.md)
```

2025-01-08 13:52 UTC, KnowWhoami requested changes

2025-01-08 13:52 UTC, KnowWhoami commented on tests/test_framework/mod.rs
> +            );
> live_contract_balance == Amount::from_btc(0.004605).unwrap() // for cases like abort3_case3: where the fauly maker doesn't recover.

This is only for the first maker as it would create funding txes of worth `0.004635 BTC` ->on broadcasting their contract txes -> 1000 sat per tx goes for mining fees and thus left ` 0.004605 BTC`.


But the test is failing in case the faulty maker is last one. As it  would forward `438642` sats in funding txes .
So its contract balance would be `435642 sats` after broadcasting those contract txes.

2025-01-08 14:08 UTC, mojoX911 commented on src/bin/maker-cli.rs
> +/// For more detailed usage information, please refer: https://github.com/citadel-tech/coinswap/blob/master/docs/app%20demos/maker-cli.md
fixed.

2025-01-08 14:10 UTC, mojoX911 commented on README.md
>  Additionally, note that this code is currently designed to run exclusively on Linux systems.
I have added that information in the text below. Better not to clutter info in the headline. Also removed the linux only note. that's also added in the installation section and doesn't have be in headline.

2025-01-08 14:14 UTC, mojoX911 commented on tests/test_framework/mod.rs
> +            );
Yes. I thought thats a problem, but it is the intended behavior. Added into another clause.

2025-01-08 15:44 UTC, KnowWhoami commented on Cargo.toml
> +homepage = "https://github.com/citadel-tech/coinswap"
why we require `homepage` field when we have `repository`?

2025-01-08 15:50 UTC, mojoX911 commented on Cargo.toml
> +homepage = "https://github.com/citadel-tech/coinswap"
some crates io requirement. doesn't matter.

2025-01-08 15:51 UTC, KnowWhoami approved these changes

2025-01-08 15:51 UTC, merged